### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by lastweek** [pulp-platform/axi_rab#2]
Hi,

Impressive work guys! I came across this repo when I was googling AXI address remap. I'm writing a design that needs this feature.  This is also the first idea came to my mind. But I was not sure how to do this in HLS C++.

Not sure if I understand it correctly, correct me if I'm wrong: This IP's purpose is to translate virtual address of a upstream AXI transaction to a downstream AXI transaction. The translation only changes the address field of Read Address Channel and Write Address channel, while other signals of AXI are preserved as is, propagated from upstream to downstream. Implementation wise, you need to cache some of the upstream AXI states if the translation is longer than 1 cycle. Is my understanding correct?

Btw, do you guys think if there are any other solutions to this? For example, let the source side use AXI-S, and use a AXI DataMover? 

Thank you.

**Comment by andreaskurth** [comment]
Hi,

> This IP's purpose is to translate virtual address of a upstream AXI transaction to a downstream AXI transaction. The translation only changes the address field of Read Address Channel and Write Address channel, while other signals of AXI are preserved as is, propagated from upstream to downstream.

Yes, at its core this module is basically an MMU stripped down to a multi-level TLB for AXI-to-AXI address translation.

> Implementation wise, you need to cache some of the upstream AXI states if the translation is longer than 1 cycle.

I am not sure what you mean by "longer than 1 cycle", since in AXI request, data, and response (the last only in write direction) are decoupled. So parts of the state always have to be preserved from one channel to an other.

> Btw, do you guys think if there are any other solutions to this? For example, let the source side use AXI-S, and use a AXI DataMover?

If your memory system and programming model favor doing the address translation ahead of time, programming a DataMover, and then streaming the data through it, that could work.

**Comment by lastweek** [comment]
Thank you for your answer @accuminium. I've read your papers about this project, and got what I need.

**Comment by andreaskurth** [comment]
Great! Glad it helped and thanks for reaching out :)
